# Generated by Django 5.2 on 2025-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0027_alter_tag_tag_name_alter_timetable_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('timetable', 'guest'), name='unique Registration'),
        ),
        migrations.AddConstraint(
            model_name='tagmap',
            constraint=models.UniqueConstraint(fields=('event', 'tag'), name='unique Tagmap'),
        ),
    ]
